### ISSUE TITLE
Flash whenever the targeted Calliope mini is in DFU mode

### ISSUE THREAD

**Issue by joernalraun** [calliope-mini/calliope-mini-flash-app-iOS#16]
Always try to flash a program when Calliope mini is in DFU mode.
Sometimes the Calliope mini is in DFU mode, but that app seems not to try to flash to it as it seem to be still waiting for a device to connect to. In this case the app should also just try to flash.

**Comment by karge-itestra** [comment]
It is not possible to flash without a connection to the device. This could be a timing issue with the search for a calliope in DFU mode.

**Comment by joernalraun** [comment]
Ah, maybe this is possible when there is a "Easy" connection aka paired Calliope mini that is in DFU mode?
